# Generated by Django 2.2.5 on 2020-01-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('cell_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('dl_num', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('cell_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('dl_num', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('van_num', models.CharField(blank=True, max_length=4)),
                ('vin', models.CharField(blank=True, max_length=60)),
                ('year_make_model', models.CharField(blank=True, max_length=128)),
                ('plate', models.CharField(blank=True, max_length=10)),
                ('tag_exp', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
